### ISSUE TITLE
Did you mean to give LEQ no constructors in ex1?

### ISSUE THREAD

**Issue by FPtje** [wouter-swierstra/TPT-2014#17]
https://github.com/wouter-swierstra/TPT-2014/blob/master/Exercise1.agda#L207

I doubt a LEQ with no constructors would be easy to use...

**Comment by wouter-swierstra** [comment]
>
>
> https://github.com/wouter-swierstra/TPT-2014/blob/master/Exercise1.agda#L207
>

Nope. Choose your own constructors :) It says so in the comment above; the
comment below is outdated.

  Wouter
